#!/usr/bin/env python3
"""Generate `requirements.txt` from `pyproject.toml`"""

import sys
import os

if sys.version_info.major < 3 or sys.version_info.minor < 11:
    print(f"{os.path.basename(sys.argv[0])}: Warning: This script requires Python 3.11+ for tomllib")
    sys.exit(0)

from pathlib import Path
from typing import Any, cast
import tomllib

script_loc = Path(__file__)
source_root = script_loc.parent.parent

def main() -> int:
    data: dict[str, Any]
    with open(source_root/'pyproject.toml', mode="rb") as project_file:
        data = tomllib.load(project_file)

    deps = cast(list[str], data['project']['dependencies'])

    rel_path = script_loc.relative_to(source_root).as_posix()

    with open(source_root/'requirements.txt', "w") as req_file:
        req_file.write( "\n".join([
                            "# **Autogenerated file**. Do not Edit",
                            f"# Generated by {rel_path}",
                            f"# Instead edit pyproject.toml and run {rel_path}"]
                            + deps) + '\n' )

    return 0

if __name__ == "__main__":
    sys.exit(main())